<?php

namespace AdLabs\SalesAdminBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CataloguesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CataloguesRepository extends EntityRepository
{
}
