datagrid:
    items_grid:
       extended_entity_name: %oro_user.entity.class%
       options:
          entityHint: user
          entity_pagination: true
       source:
          type: orm
          query:
            select:
                - u.id
                - u.username
            from:
                - {  table: %oro_user.entity.class%, alias: u }
       columns:
          id:
            label: oro.user.id.label
          username:
            label: oro.user.username.label
       properties:
          id: ~
          update_link:
              type: url
              route: oro_user_update
              params:
                - id
          view_link:
              type: url
              route: oro_user_view
              params:
                - id
          delete_link:
              type: url
              route: oro_api_delete_user
              params:
                  - id
       sorters:
          columns:
              id:
                data_name: u.id
              username:
                 data_name: u.username
          default:
              id: %oro_datagrid.extension.orm_sorter.class%::DIRECTION_ASC
       filters:
          columns:
              id:
                type: string
                data_name: u.id
              username:
                type: string
                data_name: u.username
       actions:
          view:
              type: navigate
              label: oro.grid.action.view
              link: view_link
              icon: eye-open
              acl_resource: oro_user_user_view
              rowAction: true
          update:
              type: navigate
              label: oro.grid.action.update
              link: update_link
              icon: edit
              acl_resource: oro_user_user_update
          delete:
              type: navigate
              labal: oro.grid.action.delete
              link: delete_link
              icon: trash
              acl_resource: oro_user_user_delete
    test_items_grid:
       options:
          entity_pagination: true
          skip_acl_check: true
       source:
          type: orm
          query:
            select:
              - i.id
              - i.name
              - i.brand
            from:
              - { table: AdLabsSalesAdminBundle:Items, alias: i}

       columns:
          id:
            label: id
          name:
            label: name
          brand:
            label: brand

       properties:
          id: ~
          view_link:
            type: url
            route: items_view
            params: [ id ]

       actions:
          view:
              type: navigate
              label: oro.grid.action.view
              link: view_link
              icon: eye-open
              rowAction: true
          update:
              type: navigate
              label: oro.grid.action.update
              link: update_link
              icon: edit
          delete:
              type: navigate
              labal: oro.grid.action.delete
              link: delete_link
              icon: trash